### ISSUE TITLE
Markdownの画像にアイコンが表示されてしまう

### ISSUE THREAD

**Issue by sakelog** [sakelog/sake_log#9]
## 発生事象

Markdown中に画像を表示させるとアイコンが表示されてしまう

## 発生原因

記事中の画像からオリジナル画像へのリンクが`target=_blank`で開くため。
CSSでの指定と干渉

## 今後の対策

- CSSの修正

**Comment by sakelog** [comment]
修正済み。

下記の通り修正しました。

```scss
    a[target="_blank"]{
      padding-right: 0.375rem;
  
      &::after {
        display: inline-block;
        width: 20px;
        height: 20px;
        background: url(/img/external-link.svg) no-repeat 0 0;
        background-size: 20px 20px;
        content: "";
        position: relative;
        top: 0.15625rem;
        left: 0.125rem;
      }
      &.gatsby-resp-image-link::after {
        content: none;
      }
```

`gatsby-resp-image-link`クラスで画像リンクが貼られているので、`::after`に`content: none;`を指定
